sudo: required
services:
  - docker
language: ruby
# rvm:
#   - "2.2"
#   - "2.4.2"
#   - "2.5"
#   - ruby-head
# env:
#   - "PGVERSION=10.0-1-linux-x64 PATH=\"/opt/PostgreSQL/10/bin:$PATH\""
#   - "PGVERSION=9.3.19-1-linux-x64 PATH=\"/opt/PostgreSQL/9.3/bin:$PATH\""
#   - "PGCROSS=true"
matrix:
  include:
    # i686
    - rvm: "2.5"
      env:
        - "PGVERSION=10.0-1-linux-x64"
        - "PATH=\"/opt/PostgreSQL/10/bin:$PATH\""
        - "CC=\"gcc-8 -m32\""
        - "SETARCH=\"setarch i686 --verbose --3gb\""
      addons:
        apt:
          config:
            retries: true
          update: true
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-8-multilib
  # Test cross compilation only with 2.4
  exclude:
    - rvm: "2.2"
      env: "PGCROSS=true"
    - rvm: "2.5"
      env: "PGCROSS=true"
    - rvm: ruby-head
      env: "PGCROSS=true"
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
before_install:
  - gem install bundler
  - bundle install
  # Download and install postgresql version to test against in /opt (for non-cross compile only)
  - |
    if [ -z "$PGCROSS" ]; then
      wget http://get.enterprisedb.com/postgresql/postgresql-$PGVERSION.run && \
        chmod +x postgresql-$PGVERSION.run && \
        sudo ./postgresql-$PGVERSION.run --extract-only 1 --mode unattended
    fi
before_script:
  - echo SETARCH=$SETARCH
  - $SETARCH uname -a
script: |
  if [ -z "$PGCROSS" ]; then
    rake compile test
  else
    rake gem:windows
  fi
