# Ubuntu 14.04 (Trusy)
# https://hub.docker.com/r/i686/ubuntu/
FROM i686/ubuntu:14.04

ARG PGVERSION
ARG PGPATH
ARG RUBYVERSION="2.5"

ENV PATH "${PGPATH}:${PATH}"

WORKDIR /build
COPY . .

RUN apt-get update -qq
# To use apt-add-repository command.
RUN apt-get install -y -qq software-properties-common
# A repository to add new Rubies. The default Ruby is version 1.9 on Trusty.
# https://launchpad.net/~brightbox/+archive/ubuntu/ruby-ng
RUN apt-add-repository -y ppa:brightbox/ruby-ng
RUN apt-get update
RUN apt-get install -y \
  -o Dpkg::Options::='--force-confnew' \
  ruby${RUBYVERSION} \
  ruby${RUBYVERSION}-dev \
  wget
# ruby and rubyX.Y command are installed.
RUN ruby --version
RUN wget -q http://get.enterprisedb.com/postgresql/postgresql-$PGVERSION.run
RUN chmod +x postgresql-$PGVERSION.run
RUN ./postgresql-$PGVERSION.run --extract-only 1 --mode unattended
# => error: You are trying to run a 32bit installer in a 64bit machine. The installer will exit now
# Because the used kernel is host OS's kernel. If the host OS is 64 bit, the container is also 64 bit.

CMD ["bash"]
